"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import base64

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-$z!%$k!=scdbpfbb^*jvayheeu1)pyb35a+j2zueycbs90$m!x"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}


SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False,
    'SECURITY_DEFINITIONS': {
        'access_token': {
            'type': 'Bearer',
            'in': 'header',
            'name': 'Authorization'
        }
    }
}

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "api",
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "ProductApp",
    "Project",
    "APIs",
    "RealEstateAPI",
    "InventoryManagementAPIApp",
    # 'AnonymousContact',
    'CustomerService',
    'KeyManager',
    'drf_yasg'
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "db",
        "USER": "root",
        "PASSWORD": "mysql.root@binins",
        "HOST": 'localhost',
        "PORT": ''
    },

    "message_api_db": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "message_api",
        "USER": "root",
        "PASSWORD": "mysql.root@binins",
        "HOST": 'localhost',
        "PORT": ''
    },

    "inventory_management_db": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "inventory_management",
        "USER": "root",
        "PASSWORD": "mysql.root@binins",
        "HOST": 'localhost',
        "PORT": ''
    },

    "real_estate_db": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "real_estate",
        "USER": "root",
        "PASSWORD": "mysql.root@binins",
        "HOST": 'localhost',
        "PORT": ''
    }
}

DATABASE_ROUTERS = ["APIs.routers.APIsRouter", "InventoryManagementAPIApp.routers.CustomDBRouter", "RealEstateAPI.routers.RealEstateAPIRouter"]


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_DIRS = ["static"]
STATIC_URL = "static/"

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "media/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWS_CREDENTIALS = True

PAYHERE_MERCHANT_ID = "1226344"
PAYHERE_MERCHANT_SECRET = "OTg1OTc3NjI1MjQ2MDYzNzM5NDI1OTI2ODAwNjMxOTk4NzUyNTI="

PAYHERE_API_APP_ID = "4J9MIfYf0fF4JAeqgOttFk3sXEgJ5EVyj16cLQCQZe8"
PAYHERE_API_APP_SECRET = "8LKlkemyKNn4TxkK4Tkw5p4KAlo6KUv3t49cvjDX4y5l"
PAYHERE_API_AUTHORIZATION_KEY = base64.b64encode(str(PAYHERE_API_APP_ID + ":" + PAYHERE_API_APP_SECRET).encode("utf-8"))

STRIPE_API_KEY = ""
PAYPAL_API_KEY = ""


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'your-email@gmail.com'
EMAIL_HOST_PASSWORD = 'your-app-password'


DOMAIN = "http://127.0.0.1:8000"
