# Generated by Django 4.2.14 on 2024-11-19 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="EstateStatus",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="RealEstateAPI.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RealEstate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.FloatField()),
                ("latitude", models.FloatField(null=True)),
                ("longitude", models.FloatField(null=True)),
                ("address_line_1", models.CharField(max_length=200, null=True)),
                ("address_line_2", models.CharField(max_length=200, null=True)),
                ("price", models.FloatField()),
                ("description", models.TextField(blank=True, null=True)),
                ("available_date", models.DateField(blank=True, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="RealEstateAPI.agent",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="RealEstateAPI.city",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="RealEstateAPI.estatestatus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyMedia",
            fields=[
                ("media_id", models.AutoField(primary_key=True, serialize=False)),
                ("media_path", models.FileField(upload_to="MEDIA")),
                ("is_thumbnail", models.BooleanField()),
                (
                    "real_estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="RealEstateAPI.realestate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Land",
            fields=[
                ("land_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "real_estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="RealEstateAPI.realestate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="House",
            fields=[
                ("house_id", models.AutoField(primary_key=True, serialize=False)),
                ("number_of_bedrooms", models.IntegerField()),
                ("number_of_bathrooms", models.IntegerField()),
                ("number_of_garages", models.IntegerField()),
                ("number_of_floors", models.IntegerField()),
                (
                    "real_estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="RealEstateAPI.realestate",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="city",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="RealEstateAPI.state"
            ),
        ),
    ]
