# Generated by Django 4.2.14 on 2024-12-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("RealEstateAPI", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="number_of_bathrooms",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="house",
            name="number_of_bedrooms",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="house",
            name="number_of_floors",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="house",
            name="number_of_garages",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="realestate",
            name="price",
            field=models.FloatField(default=0.0),
        ),
    ]
