# Generated by Django 4.2.14 on 2024-12-04 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("InventoryManagementAPIApp", "0005_business_type"),
        ("RealEstateAPI", "0002_alter_house_number_of_bathrooms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="business",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="InventoryManagementAPIApp.business",
            ),
        ),
        migrations.AddField(
            model_name="realestate",
            name="business",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="InventoryManagementAPIApp.business",
            ),
        ),
    ]
