# Generated by Django 4.2.14 on 2024-12-06 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("RealEstateAPI", "0003_agent_business_realestate_business"),
    ]

    operations = [
        migrations.RenameField(
            model_name="realestate",
            old_name="address_line_1",
            new_name="address",
        ),
        migrations.RemoveField(
            model_name="realestate",
            name="address_line_2",
        ),
        migrations.AddField(
            model_name="realestate",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="RealEstateAPI.country",
            ),
        ),
    ]
