# Generated by Django 4.2.14 on 2024-12-07 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("RealEstateAPI", "0004_rename_address_line_1_realestate_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realestate",
            name="city",
        ),
        migrations.AddField(
            model_name="realestate",
            name="state",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="RealEstateAPI.state",
            ),
        ),
    ]
