# Generated by Django 4.2.14 on 2024-12-07 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("RealEstateAPI", "0005_remove_realestate_city_realestate_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realestate",
            name="agent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="RealEstateAPI.agent",
            ),
        ),
    ]
