# Generated by Django 4.2.14 on 2024-12-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("RealEstateAPI", "0006_alter_realestate_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertymedia",
            name="media_path",
            field=models.FileField(upload_to="Media"),
        ),
    ]
