# Generated by Django 4.2.14 on 2024-12-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("RealEstateAPI", "0007_alter_propertymedia_media_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertymedia",
            name="media_path",
            field=models.FileField(upload_to=""),
        ),
    ]
