# Generated by Django 4.2.14 on 2024-12-13 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("RealEstateAPI", "0009_alter_house_real_estate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="estatestatus",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
