# Generated by Django 4.2.14 on 2024-12-15 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("RealEstateAPI", "0011_agentclientmessage_client_agenthasclient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="client",
            field=models.ManyToManyField(
                related_name="client",
                through="RealEstateAPI.AgentHasClient",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="agenthasclient",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Client",
        ),
    ]
