# Generated by Django 4.2.14 on 2024-12-15 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "RealEstateAPI",
            "0012_alter_agent_client_alter_agenthasclient_client_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="agenthasclient",
            name="message",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="RealEstateAPI.agentclientmessage",
            ),
        ),
    ]
