# Generated by Django 4.2.14 on 2024-12-15 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("RealEstateAPI", "0013_alter_agenthasclient_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agenthasclient",
            name="message",
        ),
        migrations.AddField(
            model_name="agentclientmessage",
            name="agent_has_client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="RealEstateAPI.agenthasclient",
            ),
        ),
    ]
