# Generated by Django 4.2.14 on 2025-02-23 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ProductApp", "0004_subscriptionplan_term"),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomersHavePlans",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.customer"
                    ),
                ),
                (
                    "plans",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ProductApp.subscriptionplan",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customer",
            name="subscription_plans",
            field=models.ManyToManyField(
                through="api.CustomersHavePlans", to="ProductApp.subscriptionplan"
            ),
        ),
    ]
