# Generated by Django 4.2.14 on 2025-03-01 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ProductApp", "0006_alter_subscriptionplan_is_recurring"),
        ("api", "0002_customershaveplans_customer_subscription_plans"),
    ]

    operations = [
        migrations.CreateModel(
            name="API",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=25, null=True)),
                ("max_calls_per_minute", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerHasAPI",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("number_of_calls", models.IntegerField(default=0)),
                (
                    "api",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.api"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.customer"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="api",
            name="customer",
            field=models.ManyToManyField(
                through="api.CustomerHasAPI", to="api.customer"
            ),
        ),
        migrations.AddField(
            model_name="api",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="ProductApp.companyproduct",
            ),
        ),
    ]
