# Generated by Django 4.2.14 on 2025-03-07 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_api_customerhasapi_api_customer_api_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="api",
            name="max_calls_per_minute",
        ),
    ]
