# Generated by Django 4.2.14 on 2025-03-08 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ProductApp", "0008_alter_subscriptionplan_api_information"),
        ("api", "0004_remove_api_max_calls_per_minute"),
    ]

    operations = [
        migrations.AddField(
            model_name="customershaveplans",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ProductApp.companyproduct",
            ),
        ),
    ]
