# Generated by Django 4.2.14 on 2025-03-11 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_customershaveplans_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("api_key", models.CharField(max_length=255)),
                ("last_used", models.DateTimeField()),
                ("remaining_requests", models.IntegerField(blank=True, null=True)),
                ("requests_made", models.IntegerField(blank=True, null=True)),
                (
                    "customers_have_plans",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.customershaveplans",
                    ),
                ),
            ],
        ),
    ]
