# Generated by Django 4.2.14 on 2025-03-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_apikey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="password_reset_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
