# Generated by Django 4.2.14 on 2025-03-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_customer_password_reset_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetRequestEmailList",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                ("code", models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
    ]
