# Generated by Django 4.2.14 on 2025-03-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_passwordresetrequestemaillist"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscription",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name="customer",
            name="subscribed_to_newsletter",
            field=models.BooleanField(default=False),
        ),
    ]
