# Generated by Django 4.2.14 on 2025-03-29 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_securityquestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityquestion",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.customer",
            ),
        ),
    ]
