# Generated by Django 4.2.14 on 2025-03-29 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_securityquestion_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityquestion",
            name="customer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.customer",
            ),
        ),
    ]
