# Generated by Django 4.2.14 on 2025-03-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_securityquestion_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="backend_progress",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="database_progress",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="frontend_progress",
            field=models.IntegerField(default=0),
        ),
    ]
