# Generated by Django 4.2.14 on 2025-03-31 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ProductApp", "0008_alter_subscriptionplan_api_information"),
        ("api", "0013_project_backend_progress_project_database_progress_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.customer",
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ProductApp.companyproduct",
            ),
        ),
    ]
