# Generated by Django 4.2.14 on 2025-04-01 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ProductApp", "0008_alter_subscriptionplan_api_information"),
        ("api", "0014_apikey_customer_apikey_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.customer",
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="customers_have_plans",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.customershaveplans",
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="last_used",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ProductApp.companyproduct",
            ),
        ),
    ]
