# Generated by Django 4.2.14 on 2025-04-02 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_alter_apikey_customer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customershaveplans",
            old_name="plans",
            new_name="plan",
        ),
    ]
