# Generated by Django 4.2.14 on 2025-04-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_rename_plans_customershaveplans_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="renew_frequency",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="apikey",
            name="renew_times",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
