# Generated by Django 4.2.14 on 2025-06-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_delete_apikey"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentReceipt",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("order_id", models.CharField(blank=True, max_length=100, null=True)),
                ("payment_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "captured_amount",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "payhere_amount",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status_message",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("status_code", models.CharField(blank=True, max_length=1, null=True)),
                ("method", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "message_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "subscription_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("items", models.CharField(blank=True, max_length=100, null=True)),
                ("currency", models.CharField(blank=True, max_length=100, null=True)),
                ("duration", models.CharField(blank=True, max_length=100, null=True)),
                ("amount", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
