# Generated by Django 4.2.14 on 2025-06-11 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_paymentreceipt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentreceipt",
            name="email",
        ),
        migrations.RemoveField(
            model_name="paymentreceipt",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="paymentreceipt",
            name="last_name",
        ),
        migrations.AddField(
            model_name="paymentreceipt",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.customer",
            ),
        ),
    ]
