# Generated by Django 4.2.14 on 2025-06-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_remove_paymentreceipt_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentreceipt",
            name="date_of_payment",
            field=models.DateField(null=True),
        ),
    ]
