# Generated by Django 4.2.14 on 2025-07-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_paymentreceipt_date_of_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_seen",
            field=models.BooleanField(default=False),
        ),
    ]
