# Generated by Django 4.2.14 on 2025-01-27 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymousUser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                ("code", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerServiceAgent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerServiceMessage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("text", models.TextField(default="", max_length=1024)),
                ("media", models.FileField(blank=True, null=True, upload_to="")),
                ("datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerServiceChat",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "anonymous_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CustomerService.anonymoususer",
                    ),
                ),
                (
                    "customer_service_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CustomerService.customerserviceagent",
                    ),
                ),
                (
                    "messages",
                    models.ManyToManyField(to="CustomerService.customerservicemessage"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customerserviceagent",
            name="clients",
            field=models.ManyToManyField(
                through="CustomerService.CustomerServiceChat",
                to="CustomerService.anonymoususer",
            ),
        ),
        migrations.AddField(
            model_name="customerserviceagent",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="customerserviceagent",
            name="users",
            field=models.ManyToManyField(
                related_name="registered_user",
                through="CustomerService.CustomerServiceChat",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
