# Generated by Django 4.2.14 on 2025-02-04 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CustomerService", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerservicechat",
            name="customer_service_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="CustomerService.customerserviceagent",
            ),
        ),
    ]
