# Generated by Django 4.2.14 on 2025-02-17 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CustomerService", "0002_alter_customerservicechat_customer_service_agent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerservicechat",
            name="messages",
        ),
        migrations.AddField(
            model_name="customerservicechat",
            name="messages",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="CustomerService.customerservicemessage",
            ),
        ),
    ]
