# Generated by Django 4.2.14 on 2025-02-17 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CustomerService", "0003_remove_customerservicechat_messages_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerservicechat",
            name="messages",
        ),
        migrations.AddField(
            model_name="customerservicemessage",
            name="customer_service_chat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="CustomerService.customerservicechat",
            ),
        ),
    ]
