# Generated by Django 4.2.14 on 2025-02-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CustomerService", "0004_remove_customerservicechat_messages_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerservicemessage",
            name="media",
            field=models.FileField(
                blank=True, null=True, upload_to="customer-service-chat/"
            ),
        ),
    ]
