# Generated by Django 4.2.14 on 2024-12-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("InventoryManagementAPIApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
            ],
        ),
    ]
