# Generated by Django 4.2.14 on 2024-12-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("InventoryManagementAPIApp", "0003_business_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=50)),
            ],
        ),
    ]
