# Generated by Django 4.2.14 on 2024-12-04 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("InventoryManagementAPIApp", "0004_businesstype"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="InventoryManagementAPIApp.businesstype",
            ),
        ),
    ]
