# Generated by Django 4.2.14 on 2024-12-15 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "InventoryManagementAPIApp",
            "0006_aisle_brand_category_manufacturer_measurementunit_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="clients",
            field=models.ManyToManyField(
                related_name="BusinessHasClient", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
