# Generated by Django 4.2.14 on 2024-11-19 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="process",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Project.processstatus",
            ),
        ),
        migrations.CreateModel(
            name="SubProcess",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                (
                    "parentProcess",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Project.process",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Project.processstatus",
                    ),
                ),
            ],
        ),
    ]
