# Generated by Django 4.2.14 on 2025-02-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProductApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyproduct",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
