# Generated by Django 4.2.14 on 2025-02-22 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ProductApp", "0002_companyproduct_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlanItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("item", models.CharField(max_length=50)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ProductApp.subscriptionplan",
                    ),
                ),
            ],
        ),
    ]
