# Generated by Django 4.2.14 on 2025-02-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProductApp", "0004_subscriptionplan_term"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="is_recurring",
            field=models.BooleanField(default=True),
        ),
    ]
