# Generated by Django 4.2.14 on 2025-02-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProductApp", "0005_subscriptionplan_is_recurring"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
    ]
