# Generated by Django 4.2.14 on 2025-03-02 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("APIs", "0001_initial"),
        ("ProductApp", "0006_alter_subscriptionplan_is_recurring"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="api_information",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="APIs.apiinfo",
            ),
        ),
    ]
