# Generated by Django 4.2.14 on 2025-03-07 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("APIs", "0002_rename_calls_per_minutes_apiinfo_calls_per_minute"),
        ("ProductApp", "0007_subscriptionplan_api_information"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="api_information",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="APIs.apiinfo",
            ),
        ),
    ]
