# Generated by Django 4.2.14 on 2025-05-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProductApp", "0008_alter_subscriptionplan_api_information"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentNotificationDetail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("information", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
