# Generated by Django 4.2.14 on 2025-06-10 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_paymentreceipt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ProductApp", "0010_paymentrequestdetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("order_id", models.CharField(max_length=255)),
                ("items", models.CharField(max_length=255)),
                ("currency", models.CharField(max_length=4)),
                ("recurrence", models.CharField(max_length=50)),
                ("duration", models.CharField(max_length=100)),
                ("amount", models.BigIntegerField(default=0)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.customer"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PaymentRequestDetail",
        ),
    ]
