# Generated by Django 4.2.14 on 2025-06-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProductApp", "0011_invoice_delete_paymentrequestdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="is_free",
            field=models.BooleanField(default=False),
        ),
    ]
