# Generated by Django 4.2.14 on 2025-07-05 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ProductApp", "0012_subscriptionplan_is_free"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpgradePlanRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "subscription_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ProductApp.subscriptionplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
