# Generated by Django 4.2.14 on 2025-07-05 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ProductApp", "0013_upgradeplanrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="upgradeplanrequest",
            name="current_plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_plan",
                to="ProductApp.subscriptionplan",
            ),
        ),
        migrations.AddField(
            model_name="upgradeplanrequest",
            name="datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="upgradeplanrequest",
            name="subscription_plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ProductApp.subscriptionplan",
            ),
        ),
    ]
