# Generated by Django 4.2.14 on 2025-08-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProductApp", "0015_reservedspot"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyproduct",
            name="offer_early_access",
            field=models.BooleanField(default=False),
        ),
    ]
