# Generated by Django 4.2.14 on 2025-08-20 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ProductApp", "0016_companyproduct_offer_early_access"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_complete", models.BooleanField(default=False)),
                ("date_time", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ProductApp.companyproduct",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
