# Generated by Django 4.2.14 on 2025-08-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProductApp", "0017_demorequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyproduct",
            name="landing_page",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
