# Generated by Django 4.2.14 on 2025-08-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ProductApp", "0018_companyproduct_landing_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="demorequest",
            name="timezone",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
