# Generated by Django 4.2.14 on 2025-04-30 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_delete_apikey"),
        ("ProductApp", "0008_alter_subscriptionplan_api_information"),
        ("APIs", "0002_rename_calls_per_minutes_apiinfo_calls_per_minute"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("api_key", models.CharField(max_length=255)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("remaining_requests", models.IntegerField(blank=True, null=True)),
                ("requests_made", models.IntegerField(blank=True, null=True)),
                (
                    "renew_frequency",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                ("renew_times", models.IntegerField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.customer",
                    ),
                ),
                (
                    "customers_have_plans",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.customershaveplans",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ProductApp.companyproduct",
                    ),
                ),
            ],
        ),
    ]
