# Generated by Django 4.2.14 on 2025-04-30 07:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("APIs", "0003_apikey"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apikey",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="apikey",
            name="product",
        ),
        migrations.RemoveField(
            model_name="apikey",
            name="renew_frequency",
        ),
        migrations.RemoveField(
            model_name="apikey",
            name="renew_times",
        ),
    ]
