# Generated by Django 4.2.14 on 2025-07-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("APIs", "0004_remove_apikey_customer_remove_apikey_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
